---
ci:
  autoupdate_schedule: quarterly
  skip:
    - poetry-lock
    - dbt-compile
    - dbt-unit-test
    - dbt-unit-test-coverage
    - sqlfluff-lint
    - check-column-desc-are-same
    - check-script-semicolon
    - check-model-columns-have-desc
    - check-model-has-description
    - check-model-has-properties-file
    - check-model-has-all-columns

default_install_hook_types: [pre-commit, post-commit]
default_stages: [pre-commit]

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        name: Don't allow commits to the main branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure files end with a newline character
        exclude_types: [svg]
      - id: mixed-line-ending
        name: Align mixed line ending
      - id: check-added-large-files
        name: Check for large files
      - id: check-json
        name: Check JSON files are valid and parseable
      - id: check-yaml
        name: Check YAML files are valid and parseable
      - id: check-toml
        name: Check TOML files are valid and parseable
      - id: check-ast
        name: Validate Python

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        name: Check that the Poetry configuration is valid
      - id: poetry-lock
        name: Check that the lock file is up-to-date

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Make code pretty

  # Testing and coverage
  - repo: local
    hooks:
      - id: dbt-compile
        name: Compile the dbt project
        entry: dotenv run -- dbt compile
        language: system
        pass_filenames: false
        always_run: true
      - id: dbt-unit-test
        name: Run dbt unit tests
        entry: dotenv run -- dbt test --select tag:unit-test
        language: system
        pass_filenames: false
        always_run: true
      - id: dbt-unit-test-coverage
        name: Generate dbt coverage report
        entry: dotenv run -- dbt-unit-test-coverage
        language: system
        pass_filenames: false
        stages: [post-commit]
        always_run: true

  # Lint and validate dbt project
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.3
    hooks:
      - id: sqlfluff-lint
        name: Lint SQL files
        files: &model-files "^billiam_database/models/.*.sql$"
        additional_dependencies:
          - duckdb==0.7.1
          - dbt-duckdb==1.5.0
          - sqlfluff-templater-dbt

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.2.1
    hooks:
      - id: check-column-desc-are-same
        name: Check column descriptions are the same
        files: *model-files
        args: &checkpoint-args-manifest
          - "--manifest"
          - "billiam_database/target/manifest.json"
      - id: check-script-semicolon
        name: Ensure that the script does not have a semicolon
        files: *model-files
        args: *checkpoint-args-manifest
      - id: check-model-columns-have-desc
        name: Check the model columns have description
        files: *model-files
        args: *checkpoint-args-manifest
      - id: check-model-has-description
        name: Check the model has description
        files: *model-files
        args: *checkpoint-args-manifest
      - id: check-model-has-properties-file
        name: Check the model has properties file
        files: *model-files
        args: *checkpoint-args-manifest
      - id: check-model-has-all-columns
        name: Check the model has all columns in the YAML file
        files: *model-files
        args:
          - "--manifest"
          - "billiam_database/target/manifest.json"
          - "--catalog"
          - "billiam_database/target/catalog.json"
