# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

files: (src/.+)|(\.github/.+)|(.+\.yml)
exclude: (target/.*|logs/.*|packages/.*|.*\.sql) # SQL files will be hooked explicitly in SQLFluff

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Don't allow commits to main branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Check files end wth a newline character
      - id: check-added-large-files
        name: Check for large files

  # Formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        name: Make code pretty

#  # SQL Linting
#  - repo: https://github.com/sqlfluff/sqlfluff
#    rev: 2.0.7
#    hooks:
#      - id: sqlfluff
#        name: Lint SQL files
#        files: "src/models/.+.sql$"
