---
ci:
  skip: [poetry-lock, dbt-compile, dbt-unit-test, dbt-unit-test-coverage]

default_install_hook_types: [pre-commit, post-commit]

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        name: Don't allow commits to the main branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure files end with a newline character
        exclude_types: [svg]
      - id: mixed-line-ending
        name: Align mixed line ending
      - id: check-added-large-files
        name: Check for large files
      - id: check-json
        name: Check JSON files are valid and parseable
      - id: check-yaml
        name: Check YAML files are valid and parseable
      - id: check-toml
        name: Check TOML files are valid and parseable
      - id: check-ast
        name: Validate Python

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
        name: Check that the Poetry configuration is valid
      - id: poetry-lock
        name: Check that the lock file is up-to-date

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        name: Make code pretty

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.0
    hooks:
      - id: sqlfluff-lint
        name: Lint SQL files
        exclude: "^.*$" # Exclude everything for now

  # Testing and coverage
  - repo: local
    hooks:
      - id: dbt-compile
        name: Compile the dbt project
        entry: dbt compile
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
      - id: dbt-unit-test
        name: Run dbt unit tests
        entry: dbt test --select tag:unit-test
        language: system
        pass_filenames: false
        stages: [pre-commit]
        always_run: true
      - id: dbt-unit-test-coverage
        name: Generate dbt coverage report
        entry: dbt-unit-test-coverage
        language: system
        pass_filenames: false
        stages: [post-commit]
        always_run: true
