---
name: billiam_database

config-version: 2
version: 0.0.0
require-dbt-version: [">=1.0.0", "<2.0.0"]

profile: default

model-paths: ["src/models"]
seed-paths: ["src/seeds"]
test-paths: ["src/tests"]
analysis-paths: ["src/analysis"]
macro-paths: ["src/macros"]
snapshot-paths: ["src/snapshots"]
asset-paths: ["src/assets"]

packages-install-path: packages
clean-targets: ["target", "logs", "packages"]

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_project_evaluator", "dbt"]

on-run-start:
  - "{{ create_udfs() }}"
on-run-end:
  - "{% if target.name == 'prod' %}DROP SCHEMA IF EXISTS dbt_test__audit CASCADE;{% endif %}"

quoting:
  database: false
  schema: false
  identifier: false

models:
  billiam_database:
    +pre-hook:
      - "SET log_query_path='logs/{{ this | replace('.', '__') }}.log';"
    +post-hook:
      - "SET log_query_path='';"
    +group: billiam

    staging:
      +materialized: view
      +schema: staging
      +access: private
      +docs:
        node_color: DarkOrange
    intermediate:
      +materialized: table
      +schema: intermediate
      +access: private
    presentation:
      +materialized: table
      +schema: presentation
      +access: public
      #      +contract:
      #        enforced: true
      +docs:
        node_color: Green

  dbt_project_evaluator:
    +enabled: false
    +schema: dbt_project_evaluator
    +docs:
      show: false
  elementary:
    +enabled: false
    +schema: elementary
    +docs:
      show: false

seeds:
  +enabled: false
  +docs:
    node_color: Gray
  billiam_database:
    +schema: raw

# https://docs.getdbt.com/reference/test-configs
tests:
  +docs:
    node_color: Indigo
    show: false
