---
# The database will be located in Docker at `/billiam/billiam.db`
services:
  metaduck:
    build:
      context: .
      dockerfile: dockerfiles/metaduck.Dockerfile
    container_name: Metaduck
    hostname: metaduck
    volumes:
      - type: bind
        source: ./dockerfiles/metaduck-data
        target: /metabase-data/
      - type: bind
        source: ./billiam_database/billiam.duckdb
        target: /billiam.duckdb
    ports: ["3000:3000"] # http://localhost:3000/
    environment:
      MB_DB_FILE: metabase-data/metabase.db
