[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "billiam-database"
version = "0.0.0"
description = "OLAP database project for life admin (feat. dbt)."
authors = ["Bilbottom"]
readme = "README.md"
keywords = ["sql", "dbt", "duckdb"]
repository = "https://github.com/Bilbottom/billiam-database"
documentation = "https://bilbottom.github.io/billiam-database/#!/overview"

# This isn't a library so there aren't any "packages" to include, but
# `poetry install` complains that:
#   > billiam_database is not a package.
#
# Poetry only supports an "application build" via its CLI by using the
# `--no-root` flag which doesn't currently exist in the `pyproject.toml`
# file configuration yet, see:
#   - https://github.com/python-poetry/poetry/issues/2458
#   - https://github.com/python-poetry/poetry/issues/1132
#
# Until this is supported, we'll have to just remember to include the
# `--no-root` flag when running `poetry install`:
#   $ poetry install --sync --no-root
packages = []

[tool.poetry.dependencies]
python = "^3.11"
dbt-core = "^1.7.0"
dbt-duckdb = "^1.7.0"
duckdb = "0.9.2"
python-dotenv = {extras = ["cli"], version = "^1.0.0"}

[tool.poetry.group]
dev.optional = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^3"
python-dotenv = {extras = ["cli"], version = "^1.0.0"}
db-query-profiler = "^0.0.6"


# https://docs.sqlfluff.com/en/stable/configuration.html#default-configuration
[tool.sqlfluff.core]
dialect = "duckdb"
templater = "dbt"
max_line_length = 120  # ...but try to stay under 80
exclude_rules = [
    "LT08",  # Blank line expected but not found after CTE closing bracket
    "ST07",  # Prefer specifying join keys instead of using USING
    "CV03",  # Trailing comma in select statement forbidden  (this is okay in DuckDB)
]

[tool.sqlfluff.templater.dbt]
project_dir = "billiam_database/"
profiles_dir = "billiam_database/"
target = "sqlfluff"


[tool.sqlfluff.indentation]
indented_joins = true
indented_using_on = true
indented_on_contents = true
template_blocks_indent = false


###
# Capitalisation bundle
# https://docs.sqlfluff.com/en/stable/rules.html#capitalisation-bundle
###

# https://docs.sqlfluff.com/en/stable/rules.html#rule-capitalisation.keywords
[tool.sqlfluff.rules.capitalisation.keywords]  # CP01
capitalisation_policy = "lower"

# https://docs.sqlfluff.com/en/stable/rules.html#rule-capitalisation.identifiers
[tool.sqlfluff.rules.capitalisation.identifiers]  # CP02
extended_capitalisation_policy = "lower"


###
# Layout bundle
# https://docs.sqlfluff.com/en/stable/rules.html#layout-bundle
###

# https://docs.sqlfluff.com/en/stable/rules.html#rule-layout.indent
[tool.sqlfluff.layout.type.indent]  # LT02
line_position = "trailing"

# https://docs.sqlfluff.com/en/stable/rules.html#rule-layout.commas
[tool.sqlfluff.layout.type.comma]  # LT04
line_position = "trailing"


###
# References bundle
# https://docs.sqlfluff.com/en/stable/rules.html#references-bundle
###

# https://docs.sqlfluff.com/en/stable/rules.html#rule-references.keywords
[tool.sqlfluff.rules.references.keywords]  # RF04
ignore_words = ["task"]

# https://docs.sqlfluff.com/en/stable/rules.html#rule-references.quoting
[tool.sqlfluff.rules.references.quoting]  # RF06
prefer_quoted_identifiers = false
prefer_quoted_keywords = true
ignore_words = ["transaction", "date"]
