[tool.poetry]
name = "billiam-database"
version = "0.0.0"
description = "OLAP database project for life admin (feat. dbt)."
authors = ["Bilbottom"]
readme = "README.md"
keywords = ["sql", "dbt", "duckdb"]
repository = "https://github.com/Bilbottom/billiam-database"
documentation = "https://bilbottom.github.io/billiam-database/#!/overview"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dependencies]
python = "^3.9"
dbt-core = "1.5.0"
dbt-duckdb = "1.5.0"
duckdb = "0.7.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
db-query-profiler = {git = "https://github.com/Bilbottom/db-query-profiler", rev = "v0.0.2"}
dbt-unit-test-coverage = {git = "https://github.com/Bilbottom/dbt-unit-test-coverage", rev = "v0.0.1"}
