---
version: 2

sources:
  - name: calendar
    description: >
      A set of calendar tables for date manipulation.

      This should plug into:

      - https://github.com/Bilbottom/sql-schema-models/tree/main/date-schema
    database: billiam
    schema: calendar
    tables: []
  - name: raw
    database: billiam
    schema: raw
    tables:
      - name: finances
        description: Item-level transaction history from 2018-01-18.
        tags: [finances]
      - name: daily_tracker
        description: Work tracker history from 2019-04-23.
        tags: [daily-tracker]
