---
project: billiam_database

default_gateway: local
gateways:
  local:
    connection:
      type: duckdb
      database: billiam_database/billiam.duckdb
      # catalogs:
      # dev: billiam_database/billiam-dev.duckdb
      # prod: billiam_database/billiam.duckdb

model_defaults:
  dialect: duckdb
  start: 2018-01-01

ignore_patterns: ["__*.sql"]

plan:
  enable_preview: true
#environment_catalog_mapping:
#  '^prod$': prod
#  '^dev$': dev
