---
name: billiam_database

config-version: 2
version: 0.0.0
require-dbt-version: [">=1.5.4", "<2.0.0"]

profile: default

asset-paths: [assets]
macro-paths: [macros]
model-paths: [models]
seed-paths: [seeds]
test-paths: [tests]
clean-targets: [target, logs, dbt_packages]

dispatch:
  - macro_namespace: dbt
    search_order: ["dbt_project_evaluator", "dbt"]

quoting:
  database: false
  schema: false
  identifier: false

on-run-start:
  - "{{ create_udfs() }}"
on-run-end:
  - "{% if target.name == 'prod' %}DROP SCHEMA IF EXISTS dbt_test__audit CASCADE;{% endif %}"

models:
  billiam_database:
    +pre-hook:
      - "SET log_query_path='billiam_database/logs/{{ this | replace('.', '__') }}.log';"
    +post-hook:
      - "SET log_query_path='';"
    +group: billiam

    staging:
      +materialized: view
      +schema: staging
      +access: private
      +docs:
        node_color: DarkOrange
    intermediate:
      +materialized: table
      +schema: intermediate
      +access: private
    presentation:
      +materialized: table
      +schema: presentation
      +access: public
      # +contract:
      #   enforced: true
      +docs:
        node_color: Green

  dbt_project_evaluator:
    +enabled: false
    +schema: dbt_project_evaluator
    +docs:
      show: false
#  elementary:
#    +enabled: false
#    +schema: elementary
#    +docs:
#      show: false

seeds:
  billiam_database:
    +enabled: true
    +schema: seeds
    counterparty_exclusions:
      +column_types:
        counterparty: varchar(32)

# https://docs.getdbt.com/reference/test-configs
tests:
  +docs:
    node_color: Indigo
    show: false
  billiam_database:
    +enabled: true
